LinkedList
foxist/labs pull request #1
Opened 2024-03-16 21:28 UTC by foxist

2024-03-16 21:30 UTC, s1me commented
супер! в таком формате будем работать. Будешь делать пул реквесты, я тут буду их просматривать и комментить. Потом в этой же ветке правишь замечания. Будут такие итерации

2024-03-16 21:32 UTC, foxist commented
Хорошо. Ощущаю себя дедом, который не понимает куда написать, чтобы ответить😂

2024-03-16 21:33 UTC, foxist commented
> супер! в таком формате будем работать. Будешь делать пул реквесты, я тут буду их просматривать и комментить. Потом в этой же ветке правишь замечания. Будут такие итерации

Пул реквесты буду делать. Ты имеешь в виду к каждой лабе? Или каждый раз нужно создавать?

2024-03-16 21:35 UTC, s1me commented
на каждый коммит

2024-03-17 14:47 UTC, s1me commented on src/main/java/lab2/LinkedList.java
> +                "head=" + head +
давай сделаем, чтобы не только значение head выводилось, а были выдны все ноды

2024-03-17 14:56 UTC, s1me commented on src/main/java/lab2/LinkedList.java
> +    public void addFirst(T data) {
а в чем разница insert и addFirst?

2024-03-17 14:56 UTC, s1me commented on src/main/java/lab2/Node.java
> +    public String toString() {
тут не критично, но почитай про класс StringBuilder

2024-03-17 17:35 UTC, foxist commented on src/main/java/lab2/LinkedList.java
> +    public void addFirst(T data) {
Забыл удалить
addFirst оставлю

2024-03-17 17:35 UTC, foxist commented on src/main/java/lab2/LinkedList.java
> +                "head=" + head +
Хорошо. Сделаю

2024-03-17 17:37 UTC, foxist commented on src/main/java/lab2/Node.java
> +    public String toString() {
Не стоило делать?
Просто мы вроде бы с тобой вчера обговорили метод toString для обоих классов

2024-03-17 17:38 UTC, foxist commented on src/main/java/lab2/LinkedList.java
> +                "head=" + head +
Здесь получается через реализацию метода get?

2024-03-17 17:41 UTC, s1me commented on src/main/java/lab2/Node.java
> +    public String toString() {
ты правильно сделал. Но когда ты вот так объежиняешь строки это не так эффективно как использовать StringBuilder. Прочитай про него.
И еще я бы все таки чуть переработал toString для листа, потому что мне не нравится как он выводится. При большом количестве нод, у тебя будет огромное количество закрывающих скобок }}}}}}}}}

2024-03-17 17:45 UTC, foxist commented on src/main/java/lab2/Node.java
> +    public String toString() {
условно должно быть {Node Data = 3, next}, {Node...}

2024-03-17 17:47 UTC, s1me commented on src/main/java/lab2/Node.java
> +    public String toString() {
можно просто вывести значения, которые лежат в списке
{1, 2, 3, 4, 5}

2024-03-17 17:48 UTC, s1me commented on src/main/java/lab2/LinkedList.java
> +                "head=" + head +
не понял что за реализация

2024-03-17 17:56 UTC, foxist commented on src/main/java/lab2/LinkedList.java
> +                "head=" + head +
Просто не понимаю, как взять Ноды в ЛинкелЛисте самом

2024-03-17 17:57 UTC, s1me commented on src/main/java/lab2/LinkedList.java
> +                "head=" + head +
пройтись по списку и посмотреть на значения

2024-03-17 18:02 UTC, foxist commented on src/main/java/lab2/Node.java
> +    public String toString() {
Чет я не понимаю, как через toString в одной строке прописать, чтобы проводились все Ноды и только значения

2024-03-17 18:04 UTC, foxist commented on src/main/java/lab2/LinkedList.java
> +                "head=" + head +
while (next != null)
return data

2024-03-17 18:10 UTC, s1me commented on src/main/java/lab2/Node.java
> +    public String toString() {
начинаешь обход с головы. Идешь пока не найдешь null. Стоя на конкретной ноде, берешь ее значение и добавляешь в строку. Потом эту строку выводишь

2024-03-17 18:24 UTC, foxist commented on src/main/java/lab2/Node.java
> +    public String toString() {
<img width="506" alt="Снимок экрана 2024-03-17 в 21 24 00" src="https://github.com/foxist/labs/assets/41263596/6dba4964-3f42-4709-9061-7fd360dd4937">

2024-03-17 18:25 UTC, foxist commented on src/main/java/lab2/Node.java
> +    public String toString() {
Я подумал что неправильно использовать цикл в toString

2024-03-17 18:26 UTC, foxist commented on src/main/java/lab2/Node.java
> +    public String toString() {
Поэтому думал, как лучше написать код, чтобы функция не использовала цикл

2024-03-17 18:39 UTC, foxist commented
<img width="474" alt="Снимок экрана 2024-03-17 в 21 35 28" src="https://github.com/foxist/labs/assets/41263596/e0c3b224-1be9-49d2-91e1-48aff41b20b5">
По поводу метода remove - решил добавить условие на проверку размера листа

2024-03-17 18:39 UTC, foxist commented
> <img alt="Снимок экрана 2024-03-17 в 21 35 28" width="474" src="https://private-user-images.githubusercontent.com/41263596/313497030-e0c3b224-1be9-49d2-91e1-48aff41b20b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDEwNjgsIm5iZiI6MTcxMDcwMDc2OCwicGF0aCI6Ii80MTI2MzU5Ni8zMTM0OTcwMzAtZTBjM2IyMjQtMWJlOS00OWQyLTkxZTEtNDhhZmY0MWIyMGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE4MzkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOGI2N2NiZGY5ZTdmMjIzNTg1MWZmY2QzYTk0Mjg2ZjMyYzdhMTk1MmY3MDAwYjJlODc5NGYyYzVmOWJiMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.70mgUhkwCjuhVBN07jyO-uQ6LcSbosdHa_KJv2BZc7M"> По поводу метода remove - решил добавить условие на проверку размера листа

Теперь NPE не будет

2024-03-17 18:43 UTC, s1me commented
мне не нравистя такое условие
1) это костыль
2) не нужно валить в кучу декремент size и логическую проверку

2024-03-18 08:03 UTC, s1me commented
мержи в мастер

2024-03-20 09:09 UTC, s1me requested changes

2024-03-20 09:09 UTC, s1me commented on src/main/java/lab1/Main.java
> +package lab1;
это уже лишнее. Предлагаю первую и третью лабы удалить отсюда. И замержить в мастер этот пул реквест. Под каждую лабу заводи отдельный ПР

2024-03-25 19:45 UTC, merged