Binary search tree
foxist/labs pull request #3
Opened 2024-03-25 20:33 UTC by foxist

2024-03-26 10:07 UTC, s1me requested changes

2024-03-26 10:07 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
> -public class BinarySearchTree<T> implements Comparator<T> {
мы ж обсуждали, что из предыдущего пул реквеста лучше удалить 1 и 3 лабы

2024-03-26 10:07 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
> +    private boolean searchHelper(Node root, int data) {
я бы подумал про другое название метода, searchHelper не в полной мере отражает смысл

2024-03-26 10:07 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
> +    private Node insertHelper(Node root, Node node) {
тут аналогично

2024-03-26 10:07 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
> +            System.out.println(data + " couldn't be found");
одного лога мало, чтобы понять удалил метод значение или нет. Вдруг у тебя может быть логика, которая требует знания удалил ноду или нет. Я бы подумал про изменение void на boolean, возвращать true, если элемент удален, false если не удалили

2024-03-26 10:07 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
> +    public void display() {
зачем этот метод? у тебя есть toSting. На toString завязаны куча инструментов, которые испоьзуются в ентрепрайз разработке

2024-03-26 10:07 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
>      public String toString() {
логику рекурсивного вывода можно перенести из display сюда

2024-03-26 18:42 UTC, foxist commented on src/main/java/lab3/BinarySearchTree.java
> -public class BinarySearchTree<T> implements Comparator<T> {
Я честно не совсем понимаю, как мне добавлять отдельную лабу в пул-реквест

2024-03-26 18:43 UTC, foxist commented on src/main/java/lab3/BinarySearchTree.java
> +    private boolean searchHelper(Node root, int data) {
хорошо

2024-03-26 18:48 UTC, foxist commented on src/main/java/lab3/BinarySearchTree.java
> +    public void display() {
Я не совсем понимаю, как работает toString. Я его вызываю, чтобы посмотреть дерево, а он получается вызывает еще сам метод toString у класс Node?

2024-03-26 18:48 UTC, foxist commented on src/main/java/lab3/BinarySearchTree.java
> +            System.out.println(data + " couldn't be found");
Хмм, хорошо. Поменяю на boolean.

2024-03-26 18:50 UTC, foxist commented on src/main/java/lab3/BinarySearchTree.java
>      public String toString() {
Да, я в принципе понял про рекурсивный вывод. Хотел исправить . Сейчас забацаю

2024-03-26 19:12 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
> -public class BinarySearchTree<T> implements Comparator<T> {
под одну лабу одна ветка. Потом из ветки делаешь PR

2024-03-27 12:02 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
> +        return "{" + stringBuilder.delete(stringBuilder.length() - 2, stringBuilder.length()) + "}";
тут мне не нравится, что у тебя есть StringBuilder и что ты просто соединяешь строки. Какое преимущество дает использование StringBuilder?

2024-03-27 12:08 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
> +        return "{" + stringBuilder.delete(stringBuilder.length() - 2, stringBuilder.length()) + "}";
не понимаю что тут происходит. Почему отнимаешь 2? Этот момент непонятен, я бы вынес в отдельный метод с говорящим названием

2024-03-27 12:11 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
>              root = node;
что ты тут пытаешься сделать?

2024-03-27 12:23 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
>              root = node;
вот это почитай https://stackoverflow.com/questions/40480/is-java-pass-by-reference-or-pass-by-value

2024-03-27 12:28 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
> +                if (size == 1)
тут очень большая вложенность. Очень трудно в голове удержать несколько уровней вложенности условия. Попробуй переписать

2024-03-29 14:35 UTC, foxist commented on src/main/java/lab3/BinarySearchTree.java
>              root = node;
Окей, прочту

2024-03-29 14:35 UTC, foxist commented on src/main/java/lab3/BinarySearchTree.java
> +                if (size == 1)
Хорошо, подумаю как можно улучшить

2024-03-29 14:35 UTC, foxist commented on src/main/java/lab3/BinarySearchTree.java
> +        return "{" + stringBuilder.delete(stringBuilder.length() - 2, stringBuilder.length()) + "}";
Работа быстрее происходит в однопоточном приложении, плюсом здесь мы с помощью метода append добавляем элементы

2024-03-29 14:35 UTC, foxist commented on src/main/java/lab3/BinarySearchTree.java
> +        return "{" + stringBuilder.delete(stringBuilder.length() - 2, stringBuilder.length()) + "}";
Отнимаю два, так как в конце последнего добавления идет ", " - то есть два символа, соответственно отнимаю два элемента последних, то есть удаляю

2024-03-30 09:53 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
> +    private boolean searchHelper(Node root, int data) {
можно подумать про название searchRecursively()

2024-03-30 11:01 UTC, s1me commented on src/main/java/lab3/BinarySearchTree.java
> +        return "{" + stringBuilder.delete(stringBuilder.length() - 2, stringBuilder.length()) + "}";
почитай про string pool в java

2024-04-10 20:20 UTC, merged